# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    nodejs: "20"
  jobs:
    pre_install:
      - npm ci
      - npm run build
    pre_build:
      - make compile
      - pybabel compile -d docs/locale --domain=iati-sphinx-theme

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

python:
  install:
    - method: pip
      path: .
