[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "iati_sphinx_theme"
readme = "README.md"
dynamic = ["version", "description"]

[project.entry-points."sphinx.html_themes"]
iati_sphinx_theme = "iati_sphinx_theme"
